spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/BOGOShop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
     ddl-auto: create #none으로 하면 기존 db 저장함
    properties:
     hibernate:
       default_batch_fetch_size: 100
     format_sql: true
    open-in-view: false #영속성 컨텍스트가 뷰 렌더링 동안에도 열려 있게 하는 설정, 지연 로딩된 엔티티를 뷰 레이어에 사용할 수 있게 함

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyewkrqwekkeWERkdfksazblYcfPQye08f7MGEWRweVA9XkHa123456

logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: DEBUG
  #org.hibernate.orm.jdbc.bind: trace
# org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6