spring:
  profiles:
    active: local
  data:
    redis:
      host : localhost
      port : 6379
  datasource:
    url: jdbc:h2:tcp://localhost/~/BOGOShop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
     ddl-auto: create #none으로 하면 기존 db 저장함
    properties:
     hibernate:
       default_batch_fetch_size: 100
       #generate_statistics: true
 #       show_sql: true
     format_sql: true

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyewkrqwekkeWERkdfksazblYcfPQye08f7MGEWRweVA9XkHa123456

logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: DEBUG
  #org.hibernate.orm.jdbc.bind: trace
# org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6